version: 2.1

orbs:
  maven: circleci/maven@1.3.0

executors:
  example:
    docker:
      - image: 'cimg/openjdk:17.0.3'

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: example