name: PR Closer

on:
  check_suite:
    types: [completed]
      


jobs:
  close-pull-request:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    name: Close Pull Request
    if: github.event.check_suite.conclusion != success
    steps:
      - uses: codelytv/no-pull-requests@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: 🙅 We don't accept Pull Requests!
